// <auto-generated />
namespace RectPacking.UI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addNameToContainer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNameToContainer));
        
        string IMigrationMetadata.Id
        {
            get { return "201406071247082_addNameToContainer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
